### ISSUE TITLE
Question - Are put of more complex Objects supported?  Are they searchable via a Lambda expression?  What do I lose when I go to Byte vs Object storage?   

### ISSUE THREAD

**Issue by andyblum** [yahoo/Oak#123]

**Comment by andyblum** [comment]
My use case is a very generic memory buffer that could be used as part of a data movement platform.   Essentially, move and process on data based on configuration convention whether that data is File, Stream, API or database.  I am looking for a buffer in the middle and want to make sure I understand architectural tradeoffs.

**Comment by sanastas** [comment]
Hello,

I am sorry for late reply, I missed this issue. 
Any Object (complex or not) is required to be serialized in order to be written into internal off-heap memory of Oak. The serialization needs to be provided by Oak's user.

We provided serializations for simple Integer, IntBuffer and String, just for convenience of the user. All the rest can be managed by Oak after serialization is provided. Therefore complex Objects are supported, if user provide the serialization methods. When you go to Byte vs Object you lose some convenience and gain performance and small memory foot-print. Pay attention that this mostly implies to forgo the Objects both in ingestion and in data access, meaning to be able to read from Buffers and manage it without de-serialization.

OakMap<K,V> supports ConcurrentNavigableMap<K, V> interface with all the consequences. However, this is not the best case for Oak performance. Constant serialization and de-serialization of the data (especially of complex Objects), may affect the performance badly. However, ingestion of data in to Oak including serialization (on the way in) was shown to still have better performance than competitors.

As I understand your use-case of buffer-in-the-middle, it is write once, then read once and delete. If so, the overhead of serialization and de-serialization should not be that big. Your gains should be higher than what you lose. Files and Streams can be transmitted to the memory mapped files (and thus off-heap buffers) very quickly. Also regarding the memory usage, considering highly intensive memory reuse required, Oak may suggest much better memory consumption than JVM's GC alternative. If you want some additional abilities from Oak, we can discuss that.
I hope I answered your questions and let me know if you have more.

Thanks,
Anastasia
